import test from 'node:test';
import assert from 'node:assert/strict';
import { adminCard, fetchWithRetry, getRiskDetections, normalizeRiskDetection, planDeliveries, recordDeliveryFailure, userCard } from '../src/core.js';

const raw={id:'event-1',detectedDateTime:'2026-08-19T00:00:00Z',userId:'user-1',userPrincipalName:'person@contoso.com',userDisplayName:'Person',riskEventType:'leakedCredentials',riskLevel:'high',riskState:'atRisk',ipAddress:'192.0.2.1',location:{city:'Seattle'}};
test('normalizes the versioned envelope',()=>{ const value=normalizeRiskDetection(raw); assert.equal(value.schemaVersion,'1.0'); assert.equal(value.source,'graph'); assert.equal(value.eventId,'event-1'); });
test('seeds first run without delivery',()=>{ const state={deliveries:{}}; const result=planDeliveries([raw],state,true); assert.equal(result.firstRun,true); assert.equal(result.deliveries.length,0); assert.equal(Object.keys(state.deliveries).length,2); });
test('deduplicates per destination',()=>{ const state={seededAt:'earlier',deliveries:{'event-1|admin':{status:'delivered'}}}; const result=planDeliveries([raw],state,true); assert.deepEqual(result.deliveries.map(x=>x.destination),['user']); });
test('accepts delayed events inside the overlap when not previously seen',()=>{ const state={seededAt:'earlier',deliveries:{}}; const delayed={...raw,detectedDateTime:'2026-08-18T03:00:00Z'}; const result=planDeliveries([delayed],state,false); assert.equal(result.deliveries.length,1); });
test('dead-letters only after repeated destination failures',()=>{ const record={status:'pending',attempts:3}; assert.equal(recordDeliveryFailure(record,new Error('transient'),new Date('2026-08-19'),5),false); assert.equal(recordDeliveryFailure(record,new Error('transient'),new Date('2026-08-19'),5),true); assert.equal(record.status,'deadLettered'); });
test('keeps the user card minimized',()=>{ const text=JSON.stringify(userCard(normalizeRiskDetection(raw))); assert.doesNotMatch(text,/leakedCredentials|192\.0\.2\.1|Seattle|riskLevel/); assert.match(text,/recipientUpn/); });
test('admin card includes investigation fields',()=>{ const text=JSON.stringify(adminCard(normalizeRiskDetection(raw))); assert.match(text,/event-1/); assert.match(text,/high leakedCredentials/); });
test('uses the largest documented page and only required Graph properties',async()=>{ let requestedUrl=''; const response={ok:true,json:async()=>({value:[raw]})}; const fetchWithRetryImpl=async(url)=>{ requestedUrl=String(url); return response; }; await getRiskDetections('token',new Date('2026-08-18'),{fetchWithRetryImpl}); assert.match(requestedUrl,/\$top=500/); assert.match(requestedUrl,/\$select=id,detectedDateTime,activityDateTime,userId,userPrincipalName,userDisplayName,riskEventType,riskDetail,riskLevel,riskState/); assert.doesNotMatch(requestedUrl,/ipAddress|location|additionalInfo/); });
test('paginates Graph results',async()=>{ let calls=0; const requested=[]; const response=(body)=>({ok:true,json:async()=>body}); const fetchWithRetryImpl=async(url)=>{ calls+=1; requested.push(String(url)); return calls===1?response({value:[raw],'@odata.nextLink':'next'}):response({value:[{...raw,id:'event-2'}]}); }; const events=await getRiskDetections('token',new Date('2026-08-18'),{fetchWithRetryImpl}); assert.equal(events.length,2); assert.equal(calls,2); assert.equal(requested[1],'next'); });
test('retries throttling without exposing the URL',async()=>{ let calls=0; const fetchImpl=async()=>{calls+=1; return {ok:calls===2,status:calls===1?429:200,headers:{get:()=> '0'}};}; const result=await fetchWithRetry('https://secret.example/token',{},{fetchImpl,delay:async()=>{},label:'Teams admin delivery'}); assert.equal(result.status,200); assert.equal(calls,2); });
test('redacts callback URLs from terminal errors',async()=>{ const fetchImpl=async()=>({ok:false,status:400,headers:{get:()=>null}}); await assert.rejects(fetchWithRetry('https://secret.example/bearer',{},{fetchImpl,label:'Teams admin delivery'}),(error)=>!error.message.includes('secret.example')&&error.message.includes('Teams admin delivery')); });
