name: azd catalog metadata

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  catalog:
    name: azd catalog metadata
    uses: nathanmcnulty/azd-reference/.github/workflows/catalog-metadata.yml@00ded1dfd645b192259296f977bb3da09c4e8165
    permissions:
      contents: read
